version: 2
global:
  private_key: matrix_key.pem
  server_name: bonjour.zone
  well_known_server_name: chat.bonjour.zone:443
  well_known_client_name: https://chat.bonjour.zone
  well_known_sliding_sync_proxy: chat.bonjour.zone:443
  server_notices:
    enabled: true
  jetstream:
    storage_path: /data
key_server: 
  database:
    connection_string: file:///data/key_server.db
room_server: 
  database:
    connection_string: file:///data/room_server.db
sync_api:
  real_ip_header: X-Real-IP
  database:
    connection_string: file:///data/sync_api.db
federation_api: 
  database:
    connection_string: file:///data/federation_api.db
relay_api: 
  database:
    connection_string: file:///data/relay_api.db
user_api:
  account_database:
    connection_string: file:///data/user_api.db
client_api:
  registration_shared_secret: ----REGISTRATION_SECRET----
media_api:
  base_path: /data/media_store
  database:
    connection_string: file:///data/media_api.db
mscs: 
  database:
    connection_string: file:///data/mscs.db
logging:
  - type: std
    level: info