version: 2
global:
  server_name: bonjour.zone
  well_known_server_name: chat.bonjour.zone:443
  well_known_client_name: https://chat.bonjour.zone
  well_known_sliding_sync_proxy: chat.bonjour.zone:443
  server_notices:
    enabled: true

  # jetstream:
  #   storage_path: ./

# media_api:
#   base_path: ./media_store

# sync_api:
#   real_ip_header: X-Real-IP

logging:
  - type: std
    level: info